name: CI/CD Docker Hub

on:
  push:
    branches:
      - staging
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set tag da imagem
        id: vars
        run: |
          if [[ "${GITHUB_REF_NAME}" == "staging" ]]; then
            echo "TAG=staging" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "TAG=prod" >> $GITHUB_ENV
          fi

      - name: Build e Push da imagem
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/node-status-app:${{ env.TAG }}

